# This is a basic workflow to help you get started with Actions

name: wps_invite

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    types: started
  schedule:
    - cron: 0 2,14 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3
      
      - name: requirements
        run: |
          pip3 install -r requirements.txt
          
      # Runs a set of commands using the runners shell
      - name: Checkin
        run: |
          s='${{ secrets.SIDLIST }}'
          t='${{ secrets.TOKEN }}'
          
          sidList='['
          token=''
          for u in ${s[*]}          
          do
            if [${#s} <> 1]; then
              s=${s}','
            fi
            s=${s}${u}
          done
          
          s=${s}']'
          for p in ${t[*]}
          do
          token=${p}
          done
          

          random_time=$(($RANDOM % 5))
          echo "等待 ${random_time} 分钟后开始发送邀请"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时:剩余 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          echo ${sidList}
          echo ${token}
          python3 wpsInvite.py ${sidList} ${token}
